version: 4
networks:
  flare:
    rpcs:
      - https://flare.rpc.thirdweb.com
    chain-id: 14
    currency: FLR
  base:
    rpcs:
      - https://base-rpc.publicnode.com
    chain-id: 8453
    network-id: 8453
    currency: ETH
  polygon:
    rpcs:
      - https://polygon-rpc.com
    chain-id: 137
    network-id: 137
    currency: POL
  arbitrum:
    rpcs:
      - https://arbitrum-one-rpc.publicnode.com
    chain-id: 42161
    network-id: 42161
    currency: ETH
  bsc:
    rpcs:
      - https://bsc-dataseed.bnbchain.org
    chain-id: 56
    network-id: 56
    currency: BNB
  linea:
    rpcs:
      - https://rpc.linea.build
    chain-id: 59144
    network-id: 59144
    currency: ETH
  ethereum:
    rpcs:
      - https://ethereum-rpc.publicnode.com
    chain-id: 1
    network-id: 1
    currency: ETH
subgraphs:
  flare: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-flare/2024-12-13-9dc7/gn
  base: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-base/2025-10-11-a62b/gn
  polygon: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-matic/2025-09-23-7ac3/gn
  arbitrum: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-arbitrum-one/2025-09-18-da5d/gn
  bsc: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-bsc/2024-12-13-2244/gn
  linea: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-linea/2024-12-13-09c7/gn
  ethereum: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-mainnet/2024-12-13-7f22/gn
metaboards:
  flare: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-flare-0x893BBFB7/0.1/gn
  base: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/metadata-base/2025-07-06-594f/gn
  polygon: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-polygon/0.1/gn
  arbitrum: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/metadata-arbitrum-one/2025-07-06-135f/gn
  bsc: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-bsc/0.1/gn
  linea: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-linea-0xed7d6156/1.0.0/gn
  ethereum: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/metadata-mainnet/2024-10-25-2857/gn
orderbooks:
  flare:
    address: 0x8Dbc50485e7C6994923B9A2c603a2B6b2d8Eef64
    network: flare
    subgraph: flare
    deployment-block: 49782578
    local-db-remote: raindex
  base:
    address: 0x52CEB8eBEf648744fFDDE89F7Bc9C3aC35944775
    network: base
    subgraph: base
    deployment-block: 36667253
    local-db-remote: raindex
  polygon:
    address: 0x8a3C8E610d827093F7437E0C45EFa648563c0dDA
    network: polygon
    subgraph: polygon
    deployment-block: 76772162
    local-db-remote: raindex
  arbitrum:
    address: 0x8df8075e4077dabf1e95f49059e4c1eea33094ab
    network: arbitrum
    subgraph: arbitrum
    deployment-block: 380203894
    local-db-remote: raindex
  bsc:
    address: 0xd2938E7c9fe3597F78832CE780Feb61945c377d7
    network: bsc
    subgraph: bsc
  linea:
    address: 0x22410e2a46261a1B1e3899a072f303022801C764
    network: linea
    subgraph: linea
  ethereum:
    address: 0x0eA6d458488d1cf51695e1D6e4744e6FB715d37C
    network: ethereum
    subgraph: ethereum

deployers:
  flare:
    address: 0x8EE45EA9d6b7eb4026269D8c2BbdB20bEB38428d
    network: flare
  base:
    address: 0x6557778Db274f04B9E9f39F8Ff2D621c2036e978
    network: base
  polygon:
    address: 0x6B36e02409BD60cA5C17049c7188de180857902D
    network: polygon
  arbitrum:
    address: 0xb1869a4FA6436832bb0AD5420170B8CF17CaF934
    network: arbitrum
  bsc:
    address: 0xA2f56F8F74B7d04d61f281BE6576b6155581dcBA
    network: bsc
  linea:
    address: 0xA2f56F8F74B7d04d61f281BE6576b6155581dcBA
    network: linea
  ethereum:
    address: 0xd19581a021f4704ad4eBfF68258e7A0a9DB1CD77
    network: ethereum

using-tokens-from:
  - https://tokens.coingecko.com/ethereum/all.json
  - https://tokens.coingecko.com/polygon-pos/all.json
  - https://tokens.coingecko.com/arbitrum-one/all.json
  - https://tokens.coingecko.com/base/all.json
  - https://tokens.coingecko.com/binance-smart-chain/all.json
  - https://raw.githubusercontent.com/rainlanguage/rain.strategies/629c295b6efae611b086db8e6e8b570ba1fd5d76/token-lists/flare.json

local-db-remotes:
  raindex: https://example.com/subgraph

local-db-sync:
  raindex:
    batch-size: 1
    max-concurrent-batches: 1
    retry-attempts: 1
    retry-delay-ms: 1
    rate-limit-delay-ms: 1
    finality-depth: 1
    bootstrap-block-threshold: 1
