version: 4
networks:
  base:
    rpcs:
      - https://base-rpc.publicnode.com
    chain-id: 8453
    network-id: 8453
    currency: ETH
  polygon:
    rpcs:
      - https://polygon.drpc.org
    chain-id: 137
    network-id: 137
    currency: POL
  arbitrum:
    rpcs:
      - https://arbitrum-one-rpc.publicnode.com
    chain-id: 42161
    network-id: 42161
    currency: ETH
subgraphs:
  base: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-base/2026-02-05-c4ef/gn
  polygon: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-matic/2025-09-23-7ac3/gn
  arbitrum: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/ob4-arbitrum-one/2025-09-18-da5d/gn
metaboards:
  base: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/metadata-base/2025-07-06-594f/gn
  polygon: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/mb-polygon/0.1/gn
  arbitrum: https://api.goldsky.com/api/public/project_clv14x04y9kzi01saerx7bxpg/subgraphs/metadata-arbitrum-one/2025-07-06-135f/gn
orderbooks:
  base:
    address: 0xe522cB4a5fCb2eb31a52Ff41a4653d85A4fd7C9D
    network: base
    subgraph: base
    deployment-block: 41747644
    local-db-remote: raindex
  polygon:
    address: 0x8a3C8E610d827093F7437E0C45EFa648563c0dDA
    network: polygon
    subgraph: polygon
    deployment-block: 76772162
    local-db-remote: raindex
  arbitrum:
    address: 0x8df8075e4077dabf1e95f49059e4c1eea33094ab
    network: arbitrum
    subgraph: arbitrum
    deployment-block: 380203894
    local-db-remote: raindex
deployers:
  base:
    address: 0xd905B56949284Bb1d28eeFC05be78Af69cCf3668
    network: base
  polygon:
    address: 0x6B36e02409BD60cA5C17049c7188de180857902D
    network: polygon
  arbitrum:
    address: 0xb1869a4FA6436832bb0AD5420170B8CF17CaF934
    network: arbitrum
using-tokens-from:
  - https://tokens.coingecko.com/polygon-pos/all.json
  - https://tokens.coingecko.com/arbitrum-one/all.json
  - https://tokens.coingecko.com/base/all.json

local-db-remotes:
  raindex: https://raindex-bootstrap-db.lon1.digitaloceanspaces.com/manifest.yaml

local-db-sync:
  base:
    batch-size: 50
    max-concurrent-batches: 1
    retry-attempts: 3
    retry-delay-ms: 1000
    rate-limit-delay-ms: 5000
    finality-depth: 4
    bootstrap-block-threshold: 300
  polygon:
    batch-size: 10
    max-concurrent-batches: 1
    retry-attempts: 3
    retry-delay-ms: 1000
    rate-limit-delay-ms: 5000
    finality-depth: 10
    bootstrap-block-threshold: 300
  arbitrum:
    batch-size: 50
    max-concurrent-batches: 1
    retry-attempts: 3
    retry-delay-ms: 1000
    rate-limit-delay-ms: 5000
    finality-depth: 30
    bootstrap-block-threshold: 2500
